apiVersion: cert-manager.io/v1
kind: ClusterIssuer 
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dombisza@gmail.com 
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          ingressClassName: cce 
          ingressTemplate:
            metadata:
              annotations:
                "kubernetes.io/elb.port": "80"
                "kubernetes.io/elb.id": "6e10ec9a-b6c7-436e-885a-b93b1874dc7d"
                "kubernetes.io/elb.class": "performance"
